package cl.aduana.gar.negocio.modelo.entidades;

import java.sql.Timestamp;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Entity class correspondiente a la tabla trazabilidad_servicios
 * TrazabilidadServicios generated by hbm2java
 */
@Entity
//@Table(schema = "GLOBAL", name = "GLO_TRAZA_SERVICIOS")
@Table(name = "GLO_TRAZA_SERVICIOS")
@SequenceGenerator(name = "traza_servicios_seq", sequenceName = "trazabilidad_servicios_id_seq")
public class TrazabilidadServicios implements java.io.Serializable {

    private static final long serialVersionUID = -2260419760079135671L;

    private Integer id;
    private String protocolo;
    private Timestamp fecha;
    private String tipo;
    private String servicio;
    private String categoria;
    private String glosa;
    private String estado;
    private String documento;

    public TrazabilidadServicios() {
    	// constructor vacio.
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "traza_servicios_seq")
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "protocolo")
    public String getProtocolo() {
        return protocolo;
    }

    public void setProtocolo(String protocolo) {
        this.protocolo = protocolo;
    }

    @Column(name = "fecha")
    public Timestamp getFecha() {
        return fecha;
    }

    public void setFecha(Timestamp fecha) {
        this.fecha = fecha;
    }

    @Column(name = "tipo")
    public String getTipo() {
        return tipo;
    }

    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    @Column(name = "servicio")
    public String getServicio() {
        return servicio;
    }

    public void setServicio(String servicio) {
        this.servicio = servicio;
    }

    @Column(name = "categoria")
    public String getCategoria() {
        return categoria;
    }

    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }

    @Lob
    @Column(name = "glosa")
    public String getGlosa() {
        return glosa;
    }

    public void setGlosa(String glosa) {
        this.glosa = glosa;
    }

    @Column(name = "estado")
    public String getEstado() {
        return estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    @Lob
    @Column(name = "documento")
    public String getDocumento() {
        return documento;
    }

    public void setDocumento(String documento) {
        this.documento = documento;
    }

}
